Improve stair generation, fixes #94
TeamTwilight/twilightforest pull request #119
Opened 2017-07-17 21:51 UTC by thehobojoe

Use top slabs instead of double slab/full block in most cases. Start general refactor of generation, lots of code can be reused in util functions. Obviously, tons more to do here.

2017-07-17 23:08 UTC, williewillus requested changes
Thanks for getting rid of all those extra prints and @params :P

2017-07-17 23:08 UTC, williewillus commented on src/main/java/twilightforest/structures/StructureTFHelper.java
> +
The generics here are unnecessary I'm pretty sure. Just use `Block` as the parameter

2017-07-17 23:08 UTC, williewillus commented on src/main/java/twilightforest/structures/StructureTFComponent.java
> +
If this doesn't hold any data can we make its methods static?

2017-07-17 23:11 UTC, williewillus commented on src/main/java/twilightforest/structures/StructureTFHelper.java
> +    }
Not sure if this is necessary vs just using getDefaultState direvtly.

2017-07-17 23:36 UTC, jsullivan-cambrian commented on src/main/java/twilightforest/structures/StructureTFHelper.java
> +
Definitely not strictly necessary, it just results in slightly more readable code imo. Can be removed if necessary.

2017-07-17 23:37 UTC, thehobojoe commented on src/main/java/twilightforest/structures/StructureTFHelper.java
> +
oops wrong account

2017-07-17 23:38 UTC, thehobojoe commented on src/main/java/twilightforest/structures/StructureTFComponent.java
> +
Yep, definitely.

2017-07-17 23:38 UTC, thehobojoe commented on src/main/java/twilightforest/structures/StructureTFHelper.java
> +    }
Same answer as above but.... yeah this is definitely the least necessary. I'll probably remove it.

2017-07-17 23:48 UTC, thehobojoe commented on src/main/java/twilightforest/structures/StructureTFHelper.java
> +
Ah I read what you wrote again - looks like you're right. Not sure why I thought I needed a generic there but apparently I don't. Doing some cleanup now.

2017-07-20 22:25 UTC, Benimatic commented
Just bumping this. Is this clear to be merged, williewillus?

2017-07-21 00:29 UTC, williewillus commented
lgtm

2017-07-21 00:29 UTC, merged