Small cleanups, insignificant terrain get speedup
TeamTwilight/twilightforest pull request #151
Opened 2017-08-28 01:52 UTC by fewizz

2017-08-28 01:53 UTC, liach commented on src/main/java/twilightforest/TwilightForestMod.java
> +		//FIXME: Reenable this once Thaumcraft is available.
It's not going to be back

2017-08-28 01:53 UTC, liach commented on src/main/java/twilightforest/entity/passive/EntityTFBunny.java
> +        this.tasks.addTask(3, new EntityAITempt(this, 1.0D, Items.GOLDEN_CARROT, true));
spaces vs tabs

2017-08-28 01:59 UTC, liach approved these changes

2017-08-28 02:10 UTC, williewillus requested changes

2017-08-28 02:10 UTC, williewillus commented on src/main/java/twilightforest/TFFeature.java
> +			//TFBiomeProvider tfManager = (TFBiomeProvider) world.getBiomeProvider();
? if the variable is unused just remove the line

2017-08-28 02:10 UTC, williewillus commented on src/main/java/twilightforest/block/enums/BossVariant.java
> +	// Caching, cos vm each time creates new array when calling values()
comment unnecessary

2017-08-28 02:10 UTC, williewillus commented on src/main/java/twilightforest/client/renderer/TFSkyRenderer.java
>  	@SideOnly(Side.CLIENT)
do not change this method or anything with [VanillaCopy] on it, the code needs to diff cleanly (or near-cleanly) with vanilla so we can track changes in vanilla properly

2017-08-28 02:10 UTC, williewillus commented on src/main/java/twilightforest/world/ChunkGeneratorTwilightForest.java
> +				Biome biomegenbase = this.biomesForGeneration[biomeForGenIndex/*ax + 2 + (az + 2) * 10*/];
don't leave random things commented in, just remove it if you're confident in the change

2017-08-28 02:10 UTC, williewillus commented on src/main/java/twilightforest/world/ChunkGeneratorTwilightForest.java
> +						float heightFactor = this.parabolicField[pfIndex/*ox + 2 + (oz + 2) * 5*/] / (rootHeight + 2.0F);
same thing here, remove comment

2017-08-28 02:10 UTC, williewillus commented on src/main/java/twilightforest/world/ChunkGeneratorTwilightForest.java
> +	}*/
if this is unused just remove it

2017-08-29 15:24 UTC, williewillus requested changes

2017-08-29 15:24 UTC, williewillus commented on src/main/java/twilightforest/client/renderer/TFSkyRenderer.java
can you undo all changes to this file?

2017-08-29 15:24 UTC, williewillus commented on src/main/java/twilightforest/TwilightForestMod.java
> -			//registerThaumcraftIntegration();
If you're going to remove this remove the actual `registerThaumcraftIntegration` method as well

2017-08-29 15:24 UTC, williewillus commented on src/main/java/twilightforest/entity/passive/EntityTFBunny.java
> +		this.tasks.addTask(3, new EntityAITempt(this, 1.0D, Items.GOLDEN_CARROT, true));
add dandelions and remove wheat seeds (see vanilla EntityRabbit)

2017-09-02 20:48 UTC, closed without merging