[Fix] Giant Tools no longer allow reach beyond for the tools themselves.
TeamTwilight/twilightforest pull request #1720
Opened 2023-01-05 20:04 UTC by bconlon1

This PR fixes issue #1660, somewhat, by making Giant Tools' reach not carry over to the player's offhand, meaning it won't apply to things like block placement. However, it does not fix the accessing GUI's part as that is mainhand behavior with the tool, so I personally view it as a nonissue/intentional, but I can implement an additional fix for that part if desired.

closes #1660

2023-01-05 20:07 UTC, Tamaized approved these changes

2023-01-05 20:28 UTC, GizmoTheMoonPig approved these changes
yeah baby

2023-02-12 21:54 UTC, Tamaized requested changes

2023-02-12 21:54 UTC, Tamaized commented on src/main/java/twilightforest/ASMHooks.java
> +		/*InteractionHand hand = ToolAbilityListener.INTERACTION_HAND;
This and below needs to be uncommented and addressed when you're ready.

2023-02-13 14:35 UTC, Tamaized approved these changes

2023-02-13 15:26 UTC, merged