Fix StackOverflowError crash in Fiery Armor
TeamTwilight/twilightforest pull request #2153
Opened 2024-06-27 21:06 UTC by Sleepy-Horse

There was a StackOverflowError crash in rendering when wearing Fiery Armor. I have fixed it.

2024-07-04 16:01 UTC, GizmoTheMoonPig requested changes
This is not the way to fix this. 

This PR removes the fullbright property of fiery armor as a side effect of deleting the model class. The proper fix here is just to add the `color` parameter to the super call.

2024-07-24 09:45 UTC, Sleepy-Horse commented
Here's the screenshot
![image](https://github.com/user-attachments/assets/d3f4e98c-5f5a-4014-8714-b781910cabfd)

2024-07-24 16:29 UTC, Tamaized commented on src/main/java/twilightforest/client/model/armor/FieryArmorModel.java
> +		super.renderToBuffer(stack, builder, 0xF000F0, overlay, 654311423);
Why 0x26FFFFFF ? Shouldn't it be 0xFFFFFFFF ?
The super uses -1 which is 0xFFFFFFFF.

2024-07-24 16:30 UTC, Tamaized commented on src/main/java/twilightforest/client/model/armor/FieryArmorModel.java
> +		super.renderToBuffer(stack, builder, 0xF000F0, overlay, 654311423);
Also use hex for colors as its much more readable than decimal.

2024-07-24 20:48 UTC, merged