update zh-cn and en-us
TeamTwilight/twilightforest pull request #412
Opened 2018-01-26 07:37 UTC by forestbat

2018-02-16 00:14 UTC, 3TUSK requested changes
RFC indicates "we want more inputs from other translators".

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
>  tile.TFTowerTranslucent.5.name=砷铅铁反应堆碎片
统一“反应堆”或者“反应器”

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +tile.TFTowerDevice.0.name=重现方块
建议把所有的“的”都加回来，不然这些实际上是偏正短语的短语听着就会像是动宾短语一样...

考虑一下：
* **激活**重现方块（*(To) Activate* the Reappearing Block）
* **激活的**重现方块（*Activated* the Reappearing Block）

下同。

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_ore_map=值这么多？
没有上下文的时候这句话缺少主语。

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_progress_yeti=顶级毛皮
Alpha Fur 怎么看都是说 Fur of Alpha Yeti。不建议改动。“首领毛皮”？RFC。

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> -advancement.twilight_progress_troll=让烈焰燃烧得更猛烈些吧！
原文如此，不建议改动。

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> -advancement.twilight_progress_castle=这就是，城堡吗……
“史诗城堡，吗……“

这样如何。

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_progress_trophy_pedestal=冠军奖杯
Trophied Champion 中被修饰的成分是 Champion。“冠军奖杯”这个偏正短语中被修饰的是“奖杯”，与原文不对应。

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_progress_knights=机关控制
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_naga_armors=蛇皮鳞甲
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_lich_scepters=三位一体！
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_dining=永暮之宴
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_ghast_trap=高塔千机
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_kill_lich=穿梭阴阳
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +item.borerEssence.name=螟虫精华
RFC

2018-02-16 00:14 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +item.arcticHelm.name=极地兜帽
RFC，下同

2018-02-16 03:19 UTC, liach commented
我觉得几个创新的翻译不错啊。

2018-02-16 03:20 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_ore_map=值这么多？
这个是进度的介绍。

2018-02-16 03:21 UTC, liach commented on src/main/resources/assets/twilightforest/lang/en_us.lang
> +advancement.twilight_kill_hydra=Hercules
:+1: for this change :smile:

2018-02-16 03:24 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_progress_yeti=顶级毛皮
底下有tooltip就没什么大关系

2018-02-16 03:25 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +tile.TFTowerDevice.0.name=重现方块
我觉得这些新的翻译已经很精练了。 而且一个方块的名字一般也不会被当成动宾短语。

2018-02-16 03:26 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +item.arcticHelm.name=极地兜帽
表示对改动点赞

2018-02-16 03:26 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +item.borerEssence.name=螟虫精华
表示对改动点赞

2018-02-16 03:26 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> -advancement.twilight_progress_troll=让烈焰燃烧得更猛烈些吧！
表示对改动点赞

2018-02-16 03:27 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> -advancement.twilight_progress_castle=这就是，城堡吗……
表示对改动点赞。所有进度语气类似，看上去更加美观。

2018-02-16 03:27 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_progress_trophy_pedestal=冠军奖杯
`大奖冠军`

2018-02-16 03:27 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_ghast_trap=高塔千机
表示对改动点赞

2018-02-16 03:28 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_dining=永暮之宴
表示对改动点赞

2018-02-16 03:28 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_kill_lich=穿梭阴阳
表示对改动点赞

2018-02-16 03:28 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_naga_armors=蛇皮鳞甲
表示对改动点赞

2018-02-16 03:28 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_lich_scepters=三位一体！
我觉得最好移除感叹号

2018-02-16 03:28 UTC, liach commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_progress_knights=机关控制
表示对改动点赞

2018-02-16 07:27 UTC, forestbat commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_naga_armors=蛇皮鳞甲
所有被“RFC”的部分都是我为了简短和整齐有意所为，也没什么more information to input。

2018-02-16 07:30 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_naga_armors=蛇皮鳞甲
@forestbat 不是你，是别的翻译者——因为带 RFC 的改动都是那种“两个都没问题”的那种。

2018-02-16 07:36 UTC, forestbat commented on src/main/resources/assets/twilightforest/lang/en_us.lang
> +advancement.twilight_kill_hydra=Hercules
thanks！@Liach

2018-02-18 01:20 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +tile.TFTowerDevice.0.name=重现方块
精炼的翻译不一定是最合适的，更何况动宾短语一般也不会拿来当作方块的名字。为了避免歧义我认为有必要把“的”加回来。

2018-02-18 01:26 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> +advancement.twilight_ore_map=值这么多？
这是进度的名字而不是介绍——即便如此，原文也是一个完整的句子（“How Can That Be Worth It?”）。

2018-02-18 01:27 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_cn.lang
> -advancement.twilight_progress_castle=这就是，城堡吗……
OK 似乎出现了一些新的情况，"So Castle Very Wow" 似乎有一个 doge 的 meme 在里面...

2018-02-18 01:27 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/en_us.lang
> +advancement.twilight_kill_hydra=Hercules
@Drullkus Thoughts on this one?

2018-02-18 01:31 UTC, Drullkus commented on src/main/resources/assets/twilightforest/lang/en_us.lang
> +advancement.twilight_kill_hydra=Hercules
The name doesn't really feel original, and I'd like this PR to stick to the Chinese locale. If you want to make a change to the English locale, it should be done in a separate PR

2018-05-08 02:43 UTC, closed without merging

2018-05-08 02:43 UTC, liach commented
可惜可惜

2018-05-08 03:23 UTC, forestbat commented
@liach 我只是关掉这个而已，以后开新的。

2018-05-08 03:46 UTC, 3TUSK commented
@forestbat 直接 push 有问题吗？

2018-05-08 05:34 UTC, forestbat commented
@3TUSK 我只是想清理下PR。