Added en_ud.lang
TeamTwilight/twilightforest pull request #431
Opened 2018-02-18 05:27 UTC by The-Fireplace

2018-02-18 05:54 UTC, williewillus commented
Is this actually a selectable locale in-game? TIL

2018-02-18 06:01 UTC, liach commented
It is. I think a final solution is to add an upside-down localization generator.

2018-02-18 06:29 UTC, Drullkus commented
<img width="629" alt="screen shot 2018-02-17 at 10 28 34 pm" src="https://user-images.githubusercontent.com/5010174/36349022-f23c2ef0-1431-11e8-95c2-5e143d74f2f0.png">

2018-03-07 20:38 UTC, xbony2 commented
👍

2018-04-06 05:38 UTC, Tamaized requested changes

2018-04-06 05:38 UTC, Tamaized commented on src/main/resources/assets/twilightforest/lang/en_ud.lang
> +twilightforest.book.lichtower.1=ǝsɹnɔ ǝɥʇ ɯoɹɟ ɔᴉᵷɐɯ ǝɥ⟘ ˙ǝɹoɟǝq uǝǝs ǝʌ,I ʎuɐ uɐɥʇ ɹǝᵷuoɹʇs 'ǝsɹnɔ ɐ ʎq pǝʇɔǝʇoɹd ǝɹɐ ɹǝʍoʇ ǝɥʇ ɟo sʞɔᴉɹq ǝɥ⟘ ˙ɹǝʍoʇ sᴉɥʇ ᵷuᴉpunoɹɹns ɐɹnɐ ǝᵷuɐɹʇs ǝɥʇ ᵷuᴉuᴉɯɐxǝ unᵷǝq
pretty sure all of these are broken. Stuff like `\u00A78` got flipped as well as the order of some of the formatting codes

2018-05-12 19:54 UTC, Drullkus commented
Changes still requested, @The-Fireplace

2018-08-28 03:26 UTC, The-Fireplace commented
I'll wait and re-do it when I get around to turning this into a gradle plugin.

2018-08-28 03:26 UTC, closed without merging