Update zh_tw.lang
TeamTwilight/twilightforest pull request #451
Opened 2018-03-20 13:40 UTC by sfs131010

2018-04-02 21:27 UTC, 3TUSK requested changes

2018-04-02 21:27 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_tw.lang
> +twilightforest.config.silent_cicadas.tooltip=讓蟬保持沉默，為那些有音效圖書館問題，或者發現牠們很煩人的人而設。
圖書館 -> 函式庫。Ref. https://zh.wikipedia.org/zh-tw/%E5%87%BD%E5%BC%8F%E5%BA%AB

2018-04-02 21:27 UTC, 3TUSK commented on src/main/resources/assets/twilightforest/lang/zh_tw.lang
> +entity.twilightforest:apocalypse_cube.name=天啟立方 [尚未實施]
NYI == Not Yet Implement. “尚無實作”？

2018-04-02 21:39 UTC, Tamaized requested changes

2018-04-02 21:39 UTC, Tamaized commented on src/main/resources/assets/twilightforest/lang/zh_tw.lang
>  entity.twilightforest:wild_boar.name=野豬
All of these `:` in the lang keys were changed to `.` long ago.
https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/resources/assets/twilightforest/lang/en_us.lang#L439-L498

2018-04-03 05:56 UTC, Tamaized approved these changes

2018-04-06 05:31 UTC, merged