Fix all translation texts in-game
TeamTwilight/twilightforest pull request #934
Opened 2020-08-23 21:35 UTC by GizmoTheMoonPig

This is a simple fix that gets rid of the missing names for blocks and items and puts in the real names. If I need to change anything please let me know.

2020-09-01 04:43 UTC, Drullkus requested changes

2020-09-01 04:43 UTC, Drullkus commented on src/main/resources/assets/twilightforest/lang/en_us.json
> -  "item.twilightforest.boarkchop": "Boarkchop",
Almost ready to merge!

Boarkchop is dropped by the Boar's loottable, as a terrible pun 😄 

If you could please re-add it, then we can merge this PR! :)

2020-09-01 04:54 UTC, Drullkus approved these changes

2020-09-01 04:56 UTC, merged

2020-09-12 00:28 UTC, ljcool2006 commented
What about the biome names?