Update zh_cn.json
TeamTwilight/twilightforest pull request #958
Opened 2020-09-05 04:37 UTC by Determancer

Improve the translation.

2021-04-12 12:12 UTC, WKyouka commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
>    "item.twilightforest.knightly_axe.tooltip": "对无护甲的目标造成额外伤害",
knightly→knightmetal

2021-04-12 12:13 UTC, WKyouka commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
> +  "item.twilightforest.quest_ram_trophy": "谜题羊奖杯",
item→block

2021-04-12 12:14 UTC, WKyouka commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
>    "block.twilightforest.oak_leaves": "暮色橡木树叶",
oak_leaves→twilight_oak_leaves

2021-04-12 12:15 UTC, WKyouka commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
>    "block.twilightforest.firefly_jar": "萤火虫罐子",
add：
  "block.twilightforest.cicada_jar": "蝉罐子",

2021-04-23 15:39 UTC, Determancer commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
>    "block.twilightforest.oak_leaves": "暮色橡木树叶",
```suggestion
  "block.twilightforest.twilight_oak_leaves": "暮色橡木树叶",
```

2021-05-03 15:06 UTC, GizmoTheMoonPig requested changes
Everything looks alright besides the missing comma. Add that in and I think we're good to go!

2021-05-03 15:06 UTC, GizmoTheMoonPig commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
>    "twilightforest.shader.final_castle": "终焉城堡"
Missing a comma here

2021-05-03 15:24 UTC, Determancer commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
>    "twilightforest.shader.final_castle": "终焉城堡"
```suggestion
  "twilightforest.shader.final_castle": "终焉城堡",
```

2021-05-03 15:31 UTC, GizmoTheMoonPig approved these changes

2021-05-04 06:35 UTC, TUsama approved these changes

2021-05-04 06:35 UTC, TUsama commented on src/main/resources/assets/twilightforest/lang/zh_cn.json
> +  "block.twilightforest.boss_spawner": "Boss刷怪笼",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

这里是否需要空格？

2021-06-01 09:15 UTC, white-ferret requested changes
Some translation suggestions:

Important:
+ config.optifine: 禁用针对 Optifine 的警告
+ config.optifine.tooltip: 禁用启动时针对 Optifine 可能引起问题的警告

Improves:
+ xxx_wall_sign: xxx告示板
+ keepsake casket: 遗物匣
+ attack.lichBomb: explosive magic -> 爆裂魔法 (Megumin meme)
+ gui.optifine.message: 暮色森林无法解决 Optifine 中的问题

2021-06-01 12:12 UTC, Determancer commented
> Some translation suggestions:
> 
> Important:
> 
> * config.optifine: 禁用针对 Optifine 的警告
> * config.optifine.tooltip: 禁用启动时针对 Optifine 可能引起问题的警告
> 
> Improves:
> 
> * xxx_wall_sign: xxx告示板
> * keepsake casket: 遗物匣
> * attack.lichBomb: explosive magic -> 爆裂魔法 (Megumin meme)
> * gui.optifine.message: 暮色森林无法解决 Optifine 中的问题

已采纳第1、2、4、6条建议，感谢帮助。
对于第3条，请参考[Minecraft_Wiki:译名标准化](url=https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)。
对于第5条，由于爆炸和爆裂两次有微妙差别，而游戏中实际效果为爆炸，所以决定不改动。

2021-07-20 14:37 UTC, GizmoTheMoonPig commented
theres a file conflict since we had to fix a certain language key here as well, so if you can fix this, we'll merge it

2021-07-20 16:25 UTC, merged