Fixes, updated and improved the horrible German translation
TeamTwilight/twilightforest pull request #96
Opened 2017-06-23 10:33 UTC by Matti-Koopa

2017-06-26 00:25 UTC, AtomicBlom requested changes

2017-06-26 00:25 UTC, AtomicBlom commented on .gitignore
> -run
Could I ask you to please give this a little cleanup?

2017-06-27 01:55 UTC, AtomicBlom approved these changes

2017-06-27 01:55 UTC, merged

2017-06-27 01:55 UTC, AtomicBlom commented
@Matti-Koopa Does this also fix https://github.com/TeamTwilight/twilightforest/issues/61?

2017-06-27 07:19 UTC, Matti-Koopa commented
Yes it does.

2017-06-27 07:42 UTC, Tamaized commented
(You can close your own issues)